# Generated by Django 3.0 on 2019-12-05 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cars', 'Cars'), ('Clothes', 'Clothes'), ('Eletronics', 'Eletronics'), ('Services', 'Services'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.CharField(max_length=400)),
                ('photo', models.FileField(upload_to='turtle_app/static/uploads/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
