# Generated by Django 3.0 on 2019-12-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_app', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='turtle_app/static/uploads/'),
        ),
    ]
